### ISSUE TITLE
Is there any way to setup zip compression level?

### ISSUE THREAD

**Issue by u20024804** [koofr/python-zipstreamer#2]
Is there any way to setup zip compression level?

**Comment by bancek** [comment]
There is no way to set the compression level. `zipstreamer` was meant for quickly and predictably building ZIP files on the fly. One of the most important features is to precalculate the ZIP file size which would be impossible with compression.

There are other similar Python libraries that support compression you could try (but don't support calculating ZIP file size in advance):

* https://github.com/SpiderOak/ZipStream
* https://github.com/allanlei/python-zipstream
* https://github.com/arjan-s/python-zipstream
